create table if not exists silver.nofluffjobs_jobs(
    id serial primary key,
    raw_job_id int references bronze.raw_jobs(id),
    external_id text not null,    
    url text not null,
    title text not null,
    daily_tasks jsonb default null,
    category text default null,
    seniority jsonb default null,
    technology text default null,
    company_url text not null,
    company_name text not null,
    description text not null,
    benefits jsonb default null,
    salary_range_bottom float default null,
    salary_range_top float default null,
    salary_period text default 'month',
    salary_currency text default 'EUR',
    required_skills jsonb default null,
    nice_to_have_skills jsonb default null,
    requirements text not null,
    posted_at timestamptz not null,
    expired_at timestamptz not null,
    regions jsonb default null,
    created_at timestamptz default now()
)