name: techmunkak
version: 0.1.0

profile: techmunkak

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

models:
  techmunkak:
    staging:
      +materialized: view
      +schema: silver
    intermediate:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold

seeds:
  techmunkak:
    +schema: silver

vars:
  site_identifier_nofluffjobs: "NoFluffJobs"
  site_identifier_justjoinit: "JustJoinIT"

  top_skills_limit: 50
  min_coccurrence_to_be_top_kill: 20

  median_monthly_salary_min: 500
  median_monthly_salary_max: 20000

  monthly_salary_min: 750
  monthly_salary_max: 25000
